# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base image
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Use a Node.js image for running the application
FROM node:18-alpine AS runner

# Set the working directory
WORKDIR /app

# Copy the node_modules from the builder stage
COPY --from=builder /app/node_modules ./node_modules

# Copy the build output and source files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src ./src

# Copy the config files
COPY package.json ./

# Set the entrypoint to start the server
CMD ["npm", "run", "start"]
